- adr/drafts/ADRx-choose_agent_programming_language.adoc
- adr/drafts/ADRx-choose_authorization_engine.adoc
- adr/drafts/ADRx-choose_orchestrator_storage_backend.adoc
- adr/drafts/ADRx-decide_reuse_of_operators.adoc
- agent programming language
- authorization engine
- orchestrator storage backend
- reuse of operators
> Added draft ADRs for the following decisions (still to be taken):

- adr/ADR004-choose_agent_programming_language.adoc
@soenkeliebau Kind of after the fact, but better late than never...
> Record the decision of the agent programming language

- adr/ADR011-directory_structure.adoc
I've briefly documented what I believe should be the correct OS paths for some of the things we need to keep on disk.
I think this is correct according to https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html but have my doubts, whether it makes sense in all cases.
Specifically I wonder about 
1. /etc/opt/stackable - I have not often seen /etc/opt used for configuration.
2. Packages - do we want to keep these in /opt under our folder root as well?
3. Service configs, similar question, should those be somewhere else then /etc/opt/stackable/serviceconfig maybe a level up at /etc/opt/serviceconfig to clearly separate them from config for our components?
> Add ADR to define default paths used by OS packages and agent

- modules/ROOT/pages/index.adoc
Based on https://repo.stackable.tech/#browse/browse looks like there's no "nightly", but there is a "dev"
> Adjust apt repo path from `deb-nightly` to `deb-dev`

- antora-playbook.yml
(The funny branch name was created by VSCode)
Also removed hdfs-operator and sorted content sources alphabetically.
Fixes #79
> Add monitoring-operator to docs

- modules/adr/nav.adoc
- modules/adr/pages/ADR012-authn_token_management.adoc
- modules/adr/pages/drafts/ADRx-authn_token_management.adoc
Rendered: https://github.com/stackabletech/documentation/blob/adr/authn-tokens/modules/adr/pages/drafts/ADRx-authn_token_management.adoc
This is a generalization of https://github.com/stackabletech/issues/issues/4, taking into account other secret types, as well as organizationally managed secrets.
Personally I'm leaning towards doing a MVP of the custom secret service. IMO, using Secrets directly won't work well for services that care about node identities (anything that's exposed outside of the cluster), and my feeling is that relying on separate operators for each kind of secret will end up with a very disjointed experience. Vault is way too ops-heavy to have a hard dependency on, and as far as I can tell their policy framework isn't powerful enough to express our needs either.
> ADR for authn token management

- modules/ROOT/nav.adoc
- modules/ROOT/pages/supported-versions.adoc
This provides a starting point for #121, pulling in the data from each supported product operator.
Depends on https://github.com/stackabletech/zookeeper-operator/pull/381.
> Document supported ZooKeeper/Kafka versions

- modules/ROOT/examples/monitoring-servicemonitor.yaml
- modules/ROOT/nav.adoc
- modules/ROOT/pages/monitoring.adoc
Fixes #131.
This is just intended as a basic getting-started guide for now. This does NOT cover:
- HA
- Prom-per-node (see https://github.com/stackabletech/issues/issues/165)
- Thanos archival
- Alerts
- Grafana
> Basic documentation on how to set up Prometheus monitoring

- modules/ROOT/pages/getting_started.adoc
- Removed references to the  Stackable Agent
- Made the examples work with both `kind` and `k3s`
- Replaced the `kafkacat` example with `kafka-topics.sh`.
- Added paragraph for `kubectl` installation.
- Formatting.
> Test and update the getting started guide.

- modules/ROOT/nav.adoc
- modules/ROOT/pages/quickstart.adoc
Mostly to give us a working link so that we can generate a QR code for the flyer.
> Add a first version of the three-minute-quickstart page. 

- supplemental-ui/partials/navbar.hbs
I added the `/nightly` to all the menu paths for now, because the links are currently broken.
> Fixed menu links now that versions are supported

- antora-playbook.yml
- local-antora-playbook.yml
- supplemental-ui/partials/navbar.hbs
This is also related to #156 
This change enables a 'stable' url which points to the latest stable version of a documentation component. For example:
https://docs.stackable.tech/airflow/stable/index.html instead of https://docs.stackable.tech/airflow/0.3/index.html
closes #198
> Enable 'stable' URLs

- modules/ROOT/pages/quickstart.adoc
The quickstart doesn't mention the required python version to run the create-test-cluster script.
> Add note about required python version to quickstart

- modules/ROOT/pages/getting_started.adoc
- modules/tutorials/pages/end-to-end_data_pipeline_example.adoc
We want to promote the use of stackablectl. This PR adds the instructions for using it to the Getting started guide as well as the Tutorial. The Helm alternative is still provided.
> Add instructions for using stackablectl instead of Helm

- antora-playbook.yml
- gitpod-antora-playbook.yml
- local-antora-playbook.yml
- modules/ROOT/pages/index.adoc
- modules/contributor/pages/development_dashboard.adoc
- modules/operators/pages/supported_versions.adoc
- modules/operators/partials/operator_doc_links.adoc
- supplemental-ui/partials/navbar.hbs
We are retiring the spark (standalone) operator (https://github.com/stackabletech/issues/issues/227) and part of that is removing the docs. This PR does that.
> Removed spark standalone everywhere

- modules/contributor/pages/adr/ADR018-product_image_versioning.adoc
- modules/contributor/pages/adr/ADR023-product-image-selection.adoc
ADR018 and ADR023 are closely related to each other. In fact there has always bean a note in 018 that we will address part of it in a later ADR, which 023 now partially covers.
This PR simply adds cross references to both ADRs, so that someone who reads either one of them in isolation is aware of the other ADR that will be of interest too.
> Added crossreferences between ADR018 and ADR023

- modules/concepts/pages/opa.adoc
> Lock Trino authz link to 0.6

- modules/ROOT/pages/index.adoc
fixes https://github.com/stackabletech/documentation/issues/279 in main
I've tried the regular anchor syntax for antora, but it didn't work. I suspect, because we made the heading with html instead of adoc. So I made the anchor also in html.
I've tested it, and search for hive will no jump to the right place.
> Added refs to the h3 headings to fix search

- Makefile
- scripts/fix_noindex.sh
fixes #324 
An attempt to remove the noindex meta tag from the redirect to hopefully get our docs indexed by google
> Added the noindex removal step to the build

- modules/contributor/pages/adr/ADR025-logging_architecture.adoc
ADR025: Disable log aggregation by default
> ADR025: Disable log aggregation by default

- modules/concepts/pages/logging.adoc
The documentation was updated to follow changes to the ADR025: https://github.com/stackabletech/documentation/pull/330
> Slight adjustments and specified enableVectorLoggingAgent explicitly

- modules/ROOT/pages/quickstart.adoc
> Use 'stackablectl' in the Quickstart

- modules/ROOT/pages/release_notes.adoc
See https://stackable-workspace.slack.com/archives/C031BTE7ZGC/p1683797224359929
Cherry-pick of #405
> Don't suggest that users delete CRDs when upgrading

- modules/ROOT/pages/getting_started.adoc
fixes #428 
N.B. should be backported to the `release/23.7` branch and docs rebuilt.
> simplify and fix getting-started page in main docs

- modules/concepts/pages/resources.adoc
This features was previously not documented
> Document StorageClass override

- Makefile
- antora-playbook.yml
- antora.yml
- gitpod-antora-playbook.yml
- local-antora-playbook.yml
- modules/ROOT/pages/getting_started.adoc
- modules/ROOT/pages/index.adoc
- modules/ROOT/pages/product-information.adoc
- modules/ROOT/pages/quickstart.adoc
- modules/ROOT/pages/release_notes.adoc
- modules/concepts/pages/logging.adoc
- modules/contributor/pages/index.adoc
- modules/contributor/pages/steps.adoc
- modules/demos/nav.adoc
- modules/tutorials/pages/authentication_with_openldap.adoc
- modules/tutorials/pages/end-to-end_data_pipeline_example.adoc
- supplemental-ui/partials/navbar.hbs
- Tracked by https://github.com/stackabletech/stackable-cockpit/issues/98
- Part of:
- https://github.com/stackabletech/stackable-cockpit/pull/101
- https://github.com/stackabletech/documentation-ui/pull/47
Supersedes #435
> docs: Add management and demo docs

- modules/concepts/examples/cluster-operations.yaml
- modules/concepts/pages/operations/cluster_operations.adoc
Rename clusterOperation flag "reconcilePaused" to "reconciliationPaused"
This change should be backported to 23.7 and 23.4.
>  Rename clusterOperation flag "reconcilePaused" to "reconciliationPaused"

- modules/ROOT/pages/quickstart.adoc
- supplemental-ui/partials/navbar.hbs
fixes #364 
requires documentation-ui feature: https://github.com/stackabletech/documentation-ui/pull/48
> Feat: versioned menu links

- modules/concepts/nav.adoc
- modules/concepts/pages/duration.adoc
Part of https://github.com/stackabletech/operator-rs/issues/649
Direct link to the change: https://deploy-preview-467--stackable-docs.netlify.app/home/nightly/concepts/duration
> feat: Add duration doc page

- modules/concepts/pages/operations/graceful_shutdown.adoc
Extracted from https://github.com/stackabletech/hdfs-operator/pull/407
> Add a high level description of graceful shutdown

- modules/concepts/pages/operations/cluster_operations.adoc
Fixes https://github.com/stackabletech/documentation/issues/469
Makes obsolete: https://github.com/stackabletech/airflow-operator/pull/338
> Document restarts

- modules/contributor/pages/steps.adoc
The backtick was missing, causing unformatted code
> chore: add missing backtick for inline code in the contributing docs

- modules/ROOT/pages/getting-started.adoc
- modules/contributor/pages/development-dashboard.adoc
The listener-operator is now one of the fundamental operators, along with the commons- and secret-operators, and should be mentioned accordingly everywhere.
> docs: Add listener-operator where missing

- antora-playbook.yml
Currently there is no way to link to the latest version by its actual version number, which is annoying. There is only the 'stable' link (i.e. https://docs.stackable.tech/home/stable/concepts/product_image_selection). Previous versions are linkable by their version number (i.e. https://docs.stackable.tech/home/23.4/concepts/product_image_selection). 
This PR adds a redirect from the actual version to 'stable'.
**Why redirect from the number to stable, and not the other way round?** Where do URLs actually end up? Users might send each other links, they are just used in the moment and then the URL doesn't really matter. For bookmarking a URL, sometimes bookmarking a link that always points to the latest docs might be better, sometimes you might want a stable link. Both are possible, just …
> Add redirect from versioned link to stable

- modules/contributor/pages/code-style-guide.adoc
This adds a rule for error variant names as discussed in today's (2024-01-17) arch meeting.
> Add error variant name rule

- modules/ROOT/nav2.adoc
- modules/ROOT/pages/export.adoc
- supplemental-ui/partials/navbar.hbs
The rendered page can be found here: https://deploy-preview-545--stackable-docs.netlify.app/home/nightly/export
@fhennig The link in the navbar is now dead for 23.11 and previous releases, do we need to back port it somehow or what would you suggest?
> Add a section on Export Controls

- modules/concepts/pages/arm64-support.adoc
Added warning for listener operator not working in 23.11.0
I've installed the ./arm.sh script on Azure and got an image pull backoff. Research showed that the pods
`k8s_external-provisioner_listener-operator-controller-deployment` and `k8s_node-driver-registrar_listener-operator-node-daemonset` are still `amd64`.
> Adding warning and hint for listener operator

- modules/contributor/pages/guidelines/logging.adoc
- modules/contributor/pages/guidelines/opa-configuration.adoc
- modules/contributor/pages/guidelines/service-discovery.adoc
> chore: Add page aliases

- modules/contributor/pages/code-style-guide.adoc
Fixes https://github.com/stackabletech/decisions/issues/1
Preview: https://deploy-preview-563--stackable-docs.netlify.app/home/nightly/contributor/code-style-guide#_error_messages
> docs: Add rule for parameterised values in error messages

- modules/concepts/pages/product-image-selection.adoc
- give a simple "TLDR" style config snippet right in the beginning
- fix some typos and wordings
- explicitly state where to find base images for custom images
> Update product image selection page

- modules/contributor/pages/testing-on-kubernetes.adoc
> Adds brief section on ctlptl and local registries for kind and mentions different Nix install options.

- modules/ROOT/pages/kubernetes.adoc
- modules/ROOT/partials/supported-kubernetes-distributions.adoc
Fixes https://github.com/stackabletech/issues/issues/434
> fix: clarify OpenShift FIPS support

- modules/contributor/pages/testing-on-kubernetes.adoc
Fixes
```
trino-operat… │ Running cmd: make regenerate-nix && nix-build . -A docker --argstr dockerName "${EXPECTED_REGISTRY}/trino-operator" && ./result/load-image | docker load
trino-operat… │ make[1]: Entering directory '/home/sbernauer/stackabletech/trino-operator'
trino-operat… │ nix run -f . regenerateNixLockfiles
trino-operat… │ error:
trino-operat… │        … while calling the 'derivationStrict' builtin
trino-operat… │ 
trino-operat… │          at /derivation-internal.nix:9:12:
trino-operat… │ 
trino-operat… │             8|
trino-operat… │             9|   strict = derivationStrict drvAttrs;
trino-operat… │              |            ^
trino-operat… │            10|
trino-operat… │ 
trino-operat… │        … while evaluating derivation 'regenerate-nix-lockfiles'
trino-operat… │ …
```
> Add flakes as experimental feature to Nix config

- modules/ROOT/pages/kubernetes.adoc
- modules/concepts/nav.adoc
- modules/concepts/pages/container-images.adoc
- modules/concepts/pages/docker-images.adoc
closes #585 
also maybe https://github.com/stackabletech/issues/issues/577
**link to the page** https://deploy-preview-605--stackable-docs.netlify.app/home/nightly/concepts/container-images
> Add page about docker images

- Makefile
- README.adoc
- modules/contributor/pages/docs/overview.adoc
- package-lock.json
- package.json
This reverts commit b9ca3cc14f23bb22a00d86e1b6a5949a5ee2e74e.
> Revert "Update UI: Add breadcrumbs to search results (#626)"

- modules/guides/pages/running-stackable-in-an-airgapped-environment.adoc
The docs currently mention Harbor, which works but is not yet officially supported by us. Thus, setting up the mirror inside the airgap registry following the current docs won't have any useful effect since Kubernetes will try to pull all images from `docker.stackable.tech` (Nexus) instead of `oci.stackable.tech`.
I changed the documentation to use Nexus instead. We can just revert this once we switch everything to Harbor.
> Use Nexus instead of Harbor in airgap docs

- modules/guides/examples/verify-signatures/stackable-image-policy.yaml
- modules/guides/examples/verify-signatures/stackable-sbom-policy.yaml
- modules/guides/pages/enabling-verification-of-image-signatures.adoc
This PR fixes two things:
1. The policy did not work as intended, since it checked if images were signed by a Github Action with the filename `build.yml`. This is true for our operators, but not for products. So it was possible to install our operators but Pods from products were wrongly blocked from starting (the filename in case of products is `release.yml`). It does not really make sense to check the filename anyway, so I relaxed the regex in that regard.
2. The policy is now more strict in other regards, because it requires that the Github Action was triggered for a commit tagged with a version number (= a release tag). The regex part `@refs/tags/\d[\d\.]+` checks that the tag starts with a digit and that digit is followed by other digits or dots. We could also make it …
> Adjust signature verification policy

- modules/ROOT/pages/release-notes.adoc
fix: added kafka 3.6.2 to deprecated list
> fix: added kafka 3.6.2 to deprecated list

- modules/ROOT/pages/release-notes.adoc
Add a note to the release notes about UIF being experimental (since it was announced in 24.3)
> docs(release-notes): Add retroactive mention of User Info Fetcher being experimental

- modules/concepts/pages/overview.adoc
- modules/concepts/pages/stackable_resource_requests.adoc
Part of https://github.com/stackabletech/documentation/issues/637
> fix: remove home component reference

- modules/concepts/pages/overview.adoc
Part of https://github.com/stackabletech/documentation/pull/635
> [!CAUTION]
> This might be a hack, and maybe the correct way is to use [`:page-aliases: ...`](https://docs.antora.org/antora/latest/page/page-aliases/), but even then since it is broken within each release that would also require PRs for each release.
01387e5958cfb2711efe2900b536aaf3bc48e649 fixes:
```
[16:23:57.555] ERROR (asciidoctor): target of xref not found: home::kubernetes.adoc
file: modules/concepts/pages/overview.adoc
source: /home/nick/dev/github.com/stackabletech/documentation/.git (branch: release/24.3)
```
Remaining errors to fix in this PR:
```
[16:23:58.557] ERROR (asciidoctor): target of xref not found: concepts:stacklet.adoc#roles
file: docs/modules/airflow/pages/usage-guide/storage-resources.adoc
source: …
```
> fix: invalid reference

- antora-playbook.yml
- local-antora-playbook.yml
- modules/concepts/pages/stackable_resource_requests.adoc
- scripts/publish-new-version.sh
> Add release branches to the playbooks for release 24.7

- modules/contributor/pages/docs/overview.adoc
- modules/contributor/pages/docs/releasing-a-new-version.adoc
- modules/contributor/pages/docs/troubleshooting-antora.adoc
During the last release we encountered some issues involving xrefs, I have now updated the troubleshooting page and docs overview explanation to make the component structure and xref mechanism more clear.
related to: https://github.com/stackabletech/documentation/issues/637
> docs: document some antora build details

- modules/contributor/nav.adoc
- modules/contributor/pages/docs/using-tab-blocks.adoc
This is an extension feature, I wanted to explicitly document it in the contribution guide
> docs: document how to use tab blocks

- .yamllint.yaml
- modules/concepts/examples/authenticationclass-keycloak.yaml
- modules/concepts/pages/authentication.adoc
Fixes #654.
- Add example TLS configuration for the OIDC provider.
- Make it clear that TLS is disabled if that section is not present.
> Clarify tls settings for OIDC providers

- modules/ROOT/pages/release-notes.adoc
This change was already added to the release-24.7 branch but needs to be in main as well so that it remains part of the record in subsequent releases.
> fix: added note about broken git-sync creds in Airflow

- antora-playbook.yml
Fixes https://github.com/stackabletech/crddocs/issues/44
This came up in https://github.com/stackabletech/crddocs/issues/44. Initial investigation revealed that the `roles-and-role-groups.html` file was not present in the stable (24.7) and nightly (soon 24.11) version of generated files when using the production antor playbook.
This playbook is used when Netlify deploys the docs using `make netlify-build`. Local builds using `make` on the other hand included the file in both versions and as such, the redirect works.
Finally, the `redirect_facility: netlify` option was identified as the cause. The generated `_redirects` file only contained a redirect from `concepts/roles-and-role-groups.html` to `concepts/stacklet.html`. This matched with the behaviour we experiences when surfing the live …
> fix: Remove redirect_facility to fix broken redirects

- modules/ROOT/pages/release-notes.adoc
Part of https://github.com/stackabletech/issues/issues/647.
Product Features are being compiled here: https://github.com/stackabletech/issues/issues/647#issuecomment-2472978171
> Add 24.11 Release Notes

- modules/ROOT/pages/getting-started.adoc
> [!CAUTION]
> This same change needs bringing over to release/24.11 as it was accidentally in the release procedure list after the release branch has been created.
> docs(getting-started): Update version references

- antora-playbook.yml
- local-antora-playbook.yml
Created by https://github.com/stackabletech/documentation/blob/f512576917edf092c5da60cfd35ec877446e1a1f/scripts/publish-new-version.sh
> chore: Add release branches to the playbooks for release 24.11

- .github/PULL_REQUEST_TEMPLATE/release-notes.md
- .markdownlint.yaml
Part of https://github.com/stackabletech/issues/pull/680.
> fix: Remove frontmatter from release-notes template

- modules/ROOT/pages/quickstart.adoc
Follow up of https://github.com/stackabletech/documentation/pull/691 but adding the change also to the current release docs
> docs: update stackablectl version in quickstart

- modules/contributor/pages/adr/ADR029-database-connection.adoc
Links to https://github.com/stackabletech/issues/issues/681
> ADR29: Link to related issue

- modules/guides/pages/kubernetes-cluster-domain.adoc
Documentation for https://github.com/stackabletech/operator-rs/pull/939
> docs: add hint regarding cluster domain to improve DNS performance

- modules/guides/pages/kubernetes-cluster-domain.adoc
We decided to default to `cluster.local` again as cluster domain and for now only add experimental support for FQDNs.
For details, see related change in operator-rs: https://github.com/stackabletech/operator-rs/pull/947
This reverts commit 37e194dd2d13d9b3f11dd34165b621a1c9fdee62.
> revert: default cluster domain is now `cluster.local` again

- modules/ROOT/pages/getting-started.adoc
Part of https://github.com/stackabletech/docker-images/issues/968.
> chore(kafka): Set productVersion to 3.9.0 in getting_started

- modules/ROOT/pages/kubernetes/index.adoc
- modules/ROOT/pages/product-information.adoc
- modules/ROOT/partials/release-notes/release-24.11.adoc
- modules/ROOT/partials/supported-kubernetes-versions.adoc
For supported Kubernetes versions, refer to the release docs rather have an extra place that needs to be maintained.
See: 
- https://deploy-preview-707--stackable-docs.netlify.app/home/nightly/product-information/#_kubernetes
- https://deploy-preview-707--stackable-docs.netlify.app/home/nightly/kubernetes/#supported-production-distributions
This removes a point of redundancy, but does result in a link to all release info where one might expect to see information pertinent to the current release (which then has to be maintained separately to the release docs).
> fix: Refer supported k8s versions to release notes

- modules/ROOT/pages/getting-started.adoc
Part of https://github.com/stackabletech/docker-images/issues/966
> docs(getting_started): Revert NiFi example back to 1.28.1

- modules/ROOT/nav1.adoc
- modules/ROOT/pages/kubernetes/huawei-cloud.adoc
- modules/ROOT/pages/kubernetes/ibm-cloud.adoc
- modules/ROOT/pages/kubernetes/index.adoc
- modules/ROOT/pages/kubernetes/microk8s.adoc
- modules/ROOT/pages/kubernetes/vmware_tanzu.adoc
- modules/ROOT/pages/product-information.adoc
- modules/ROOT/partials/supported-kubernetes-distributions.adoc
- modules/ROOT/partials/tested-kubernetes-distributions.adoc
Outcome of talking to a prospect.
I only want to add Tanzu, don't care to much about the other changes.
Please feel free to edit this branch directly if you have feelings!
> Add VMWare Tanzu notes. Also differentiate between supported and tested k8s

- antora-playbook.yml
- local-antora-playbook.yml
This is a manual adjustment, which was also required for 24.11, see https://github.com/stackabletech/documentation/commit/fb38737843f6b174127210cd3c69c793f9f37f9f.
> fix: Adjust branch names in Antora playbooks

- modules/ROOT/partials/release-notes/release-template.adoc
Part of https://github.com/stackabletech/infrastructure/issues/142
Updating the helm install commands in the release notes template was missed during Harbor migration of the docs.
> docs: Update helm install commands

- modules/concepts/nav.adoc
- modules/concepts/pages/observability/telemetry.adoc
Part of https://github.com/stackabletech/issues/issues/639
> docs: Add telemetry documentation page

- modules/ROOT/partials/release-notes/release-25.3.adoc
Add stackabletech/hdfs-operator#634 to the release notes of SDP 25.3
This pull request will be back-ported to the release branch.
> Add hdfs-operator#634 to the release notes of SDP 25.3

- modules/ROOT/partials/release-notes/release-template.adoc
Follow up to https://github.com/stackabletech/stackable-cockpit/pull/379
Adds single command instruction for release upgrade to the release notes template
> chore: update release notes with stackablectl release upgrade instruction

- modules/concepts/pages/service-exposition.adoc
> chore: Update Service exposition concepts page (backport)

- modules/concepts/pages/operations/pod_disruptions.adoc
Backports docu on PDBs from https://github.com/stackabletech/documentation/pull/769
> Add known issue on PDBs and certificate rotation (backport)

- modules/ROOT/partials/release-notes/release-25.7.adoc
This was missed in the release notes, as the `release-notes` label was missing. This came up in https://github.com/stackabletech/trino-operator/issues/792.
This change will also be cherry-picked onto the `release-25.7` branch once merged on `main`.
> docs: Mention missed Trino PVC removal/fix in 25.7.0 release notes

- modules/ROOT/partials/release-notes/release-25.7.adoc
> docs(cherry-pick): Mention missed Trino PVC removal/fix in 25.7.0 release notes

- modules/ROOT/pages/getting-started.adoc
Part of https://github.com/stackabletech/docker-images/issues/1275
> chore: Bump zookeeper version for 25.11.0
