stackabletech/documentation

- adr/ADR004-systemd_unit_file_location.adoc
I've investigated possibilities of where to place systemd unit files and drafted an ADR with what I think is the best way forward for now.
> Add ADR for systemd unit file handling decision.

- adr/ADR004-systemd_unit_file_location.adoc
Added Oliver to the list of deciders after he had a chance to take a look as well.
> Systemd ohessel

- .github/dependabot.yml
- .github/workflows/deploy.yml
- LICENSE
- Build site on PR
- Add license
- Change dependabot to run weekly and set reviewer & labels
> Bring project up to best practices

- antora.yml
- modules/ROOT/nav.adoc
- modules/ROOT/pages/paths.adoc
> Adds a simple page documenting paths used in our distribution.

- modules/ROOT/pages/getting_started.adoc
- modules/adr/nav.adoc
Addresses the docs-related parts of #91. Trying to stick to one commit per papercut, so that it's easy to back one of them out if it proves to be controversial.
> Start addressing papercuts

- antora-playbook.yml
- gitpod-antora-playbook.yml
- local-antora-playbook.yml
#115 This makes the Druid documentation appear in the bottom left documentation selector.
> #115 - Add Druid to the overall documentation

- antora-playbook.yml
- gitpod-antora-playbook.yml
- local-antora-playbook.yml
Added documentation for the airflow-operator.
> Add airflow operator to Antora playbooks (#155)

- modules/ROOT/pages/supported-versions.adoc
> Include all products in the supported versions list

- modules/contributor/pages/adr/ADR013-user_authentication_for_products.adoc
Superseding https://github.com/stackabletech/documentation/pull/143
Part of https://github.com/stackabletech/issues/issues/170
> Add ADR013: User Authentication for Products

- antora-playbook.yml
- docker-antora-playbook.yml
- gitpod-antora-playbook.yml
- local-antora-playbook.yml
- package-lock.json
- package.json
I'm not sure if https://github.com/Mogztter/asciidoctor-kroki is the right tool to use.
But I'm to stupid to install https://github.com/asciidoctor/asciidoctor-diagram
Anyone who knows this npm/ruby/gem/whatever stuff please feel free to tell me how to do it the right way
> Add support for plantuml

- modules/contributor/pages/adr/ADR017-tls_authentication.adoc
Trying to avoid some confusion :)
> Improve docs for ADR 17

- antora-playbook.yml
- local-antora-playbook.yml
We have our first operator now that has a tagged version as well as a nightly version - the airflow operator.
This PR enables that the tagged version is also displayed, and it also enables this for all other operators.
> Enabled tags

- modules/concepts/pages/s3.adoc
- modules/reference/pages/s3.adoc
Fixed a few typos in the S3 concepts/resource docs.
> S3 documentation - minor fixes

- antora-playbook.yml
- local-antora-playbook.yml
- supplemental-ui/partials/navbar.hbs
- Added repo link
- Added stackablectl to the main menu for now
> Added stackablectl

- renovate.json
> Fixed syntax error in renovate file

- modules/contributor/pages/adr/ADR022-spark-history-server.adoc
- modules/contributor/partials/current_adrs.adoc
Fixes https://github.com/stackabletech/spark-k8s-operator/issues/84
> Spark History Server ADR

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- antora-playbook.yml
Fixes #269 
The solution described in #269 is implemented.
This pull request will be postponed until the release 22.09 is done.
> Adapt GitHub workflows to produce versioned platform documentation

- package-lock.json
There were changes in the UI repository: https://github.com/stackabletech/documentation-ui/pull/16
This updates the reference in the submodule to the latest changes.
closes https://github.com/stackabletech/documentation/issues/232
> Updated UI

- modules/concepts/pages/resources.adoc
- modules/concepts/pages/stackable_resource_requests.adoc
Part of https://github.com/stackabletech/documentation/issues/263
> Extract stackable resource to separate file.

- modules/concepts/pages/opa.adoc
> Lock Trino authz link to 0.4

- antora-playbook.yml
- gitpod-antora-playbook.yml
- local-antora-playbook.yml
- modules/concepts/pages/opa.adoc
> Fix link to trino authorization

- modules/ROOT/pages/getting_started.adoc
Thanks to @pipern for spotting this!
> fix: removed unused nifi selector in wrong place

- modules/ROOT/pages/index.adoc
One Apache too much snuck in that page.
> Fix project overview typo

- local-antora-playbook.yml
- modules/contributor/pages/adr/ADR026-affinities.adoc
- modules/contributor/partials/current_adrs.adoc
For https://github.com/stackabletech/issues/issues/323
> Add ADR 26 on affinities

- modules/ROOT/pages/release_notes.adoc
Release notes for SDP 23.4
N.B. check the text in the `stackablectl release list` output (should match https://github.com/stackabletech/release/pull/22/files)
N.B. check correctness of deleting CRDs rather than applying them
N.B. check links that assume "stable"
> release 23.4 notes

- modules/concepts/pages/pvc.adoc
Airflow doens't use PVCs anymore, we use git-sync now.
> removed PVC reference to Airflow

- modules/concepts/pages/service_discovery.adoc
For https://github.com/stackabletech/zookeeper-operator/issues/677
> Document users are responsible to keep external discovery CM up-to-date

- modules/ROOT/pages/release_notes.adoc
Supersedes https://github.com/stackabletech/documentation/pull/407
> Backport 23.4.1 release notes to 23.4

- modules/concepts/pages/overrides.adoc
Fixup of https://github.com/stackabletech/documentation/pull/415
> docs: Document user overrides (part 2)

- modules/tutorials/examples/verify-signatures/kyverno-policy.yaml
- modules/tutorials/nav.adoc
- modules/tutorials/pages/enabling_verification_of_image_signatures.adoc
Fixes https://github.com/stackabletech/documentation/issues/422
> Tutorial: Verify image signatures

- modules/ROOT/pages/release_notes.adoc
- modules/tutorials/nav.adoc
Rendered view: https://deploy-preview-420--stackable-docs.netlify.app/home/nightly/release_notes.html
> R23.7 notes

- modules/concepts/pages/overrides.adoc
For https://github.com/orgs/stackabletech/discussions/30
> Document empty string for configOverride

- modules/contributor/pages/adr/ADR023-product-image-selection.adoc
- modules/contributor/pages/adr/ADR028-automatic-stackable-version.adoc
- modules/contributor/partials/current_adrs.adoc
Part of https://github.com/stackabletech/issues/issues/404
> Add ADR 28 on Automatic stackable version selection

- modules/ROOT/pages/getting_started.adoc
Part of https://github.com/stackabletech/issues/issues/404
> Remove stackableVersion from getting started guide

- modules/ROOT/pages/release_notes.adoc
- modules/tutorials/pages/authentication_with_openldap.adoc
Part of https://github.com/stackabletech/stackable-cockpit/pull/101
> fix(docs): Update invalid xrefs for 23.1

- modules/contributor/pages/code-style-guide.adoc
> edit: fix typo in code style guide

- modules/contributor/pages/code-style-guide.adoc
> docs: Add Cargo.toml style guide

- modules/concepts/pages/labels.adoc
Part of https://github.com/stackabletech/issues/issues/188
Adjusts the label page according to the decisions made in the meeting on 2024-02-01.
> chore: Adjust labels page

- antora.yml
This needs to be cherry picked to all other branches, and set to true for 23.1 (and earlier releases)
> feat: add end-of-life flag

- modules/contributor/pages/docs/style-guide.adoc
> feat: mention the apache naming guide in the docs style guide

- antora.yml
- modules/guides/nav.adoc
- modules/guides/pages/custom-images.adoc
- modules/tutorials/nav.adoc
closes #568 
this is a _guide_, and I added it to a new section, that I will expand on in the future. some of the tutorials will be moved here, as they are actually guides.
you can read more about the difference here: https://diataxis.fr/tutorials-how-to/
> feat: custom images guide

- local-antora-playbook.yml
- package-lock.json
- package.json
~~requires the UI PR: https://github.com/stackabletech/documentation-ui/pull/61/files to be merged and then referenced here too~~
closes #208
> feat: add tab groups

- modules/ROOT/pages/kubernetes/huawei-cloud.adoc
- modules/ROOT/pages/kubernetes/ibm-cloud.adoc
- modules/ROOT/partials/supported-kubernetes-distributions.adoc
> Link to detail pages in k8s listing

- Makefile
- README.adoc
- modules/contributor/pages/docs/overview.adoc
- package-lock.json
- package.json
closes https://github.com/stackabletech/documentation/issues/615
> Update UI: Add breadcrumbs to search results

- modules/ROOT/pages/getting-started.adoc
- Stackable release
- Product versions
> docs(getting-started): Update version references

- modules/concepts/pages/stackable_resource_requests.adoc
Part of https://github.com/stackabletech/documentation/issues/637
> fix: remove home component reference

- package-lock.json
~~references a non-stable UI branch - don't merge~~
~~relevant UI branch: https://github.com/stackabletech/documentation-ui/pull/73~~
> UI Redesign

- .github/workflows/pr_pre-commit.yml
- .markdownlint.yaml
- .pre-commit-config.yaml
- .yamllint.yaml
Part of https://github.com/stackabletech/issues/issues/637
This PR adds a `pre-commit` workflow and accompanying config files.
> ci: Add pre-commit workflow

- modules/ROOT/nav1.adoc
- modules/ROOT/pages/kubernetes/eks.adoc
Ran into this preparing a customer demo on EKS using replicated
> Add docs on how to mark StorageClass as default in AWS

- modules/concepts/pages/containerdebug.adoc
Followup to #699, https://github.com/stackabletech/containerdebug/pull/23
> Update the containerdebug interval

- modules/ROOT/pages/getting-started.adoc
Part of https://github.com/stackabletech/docker-images/issues/966.
> docs(getting_started): Bump NiFi version

- modules/concepts/pages/s3.adoc
> docs: Add example about overriding the S3 region

- modules/ROOT/pages/getting-started.adoc
Part of https://github.com/stackabletech/docker-images/issues/1079
> docs(getting_started): Update Nifi to 2.4.0

- modules/ROOT/partials/release-notes/release-25.3.adoc
Back-port  #744 to the release branch
> Add hdfs-operator#634 to the release notes of SDP 25.3

- antora.yml
> chore: Set 24.3 to end of life
